
server:
  port: 80
  servlet:
    context-path: /Netdisk


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.253.99:3306/netdisk?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: gangballs
    password: Where.gangballs123
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: classpath:dist/,file:/usr/local/MyTomcat/static
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3
    # password:
    pool:
      minIdle: 1
      maxIdle: 10
      maxWait: 3
      maxActive: 8
  main:
    allow-bean-definition-overriding: true

