
server:
  port: 80
  servlet:
    context-path: /gangballs


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.253.99:3306/netdisk?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: gangballs
    password: Where.gangballs123
  security:
    user:
      1name: admin
      1password: admin

