
server:
  port: 80
  ssl:
    key-store: classpath:virtualpuffer.top.jks
    key-store-password: 123333
    key-store-type: JKS
    enabled: false
  servlet:
    context-path: /Netdisk


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.253.99:3306/netdisk?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: Where.1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: classpath:dist/,file:/usr/local/MyTomcat/static,file:/usr/local/MyTomcat/dist,file:/usr/local/MyTomcat/wife
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3
    # password:
    pool:
      minIdle: 1
      maxIdle: 10
      maxWait: 3
      maxActive: 8
  main:
    allow-bean-definition-overriding: true
  socket:
    port: 10004
    pool-keep: 20
    pool-core: 10
    pool-max: 30
    pool-queue-init: 10
  appSocket:
    port: 10005

